[package]
name = "pwrust_lib"
version = "0.0.1"
authors = ["vdallco"]
edition = "2021"

[dependencies]
reqwest = "0.11"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde =  { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0.108"